/**
 * 공공데이터포털 활용신청 TOP CSV(6종) 기반 전국 30종 활용 로드맵.
 * 서울 30종(SEOUL_DATASET_CATALOG)과 병행 — 인기·전국 API/파일 데이터 우선순위.
 */
import { scorePopularity } from "@/lib/public-data/popularity-rankings";
import { getNationalPlanCapability } from "@/lib/national-data/capability";

export type NationalDatasetPhase = 1 | 2 | 3;
export type NationalDatasetKind = "openapi" | "file" | "hybrid";
export type NationalIntegrationStatus = "live" | "partial" | "planned" | "sample";

export type NationalUtilizationPlan = {
  id: string;
  title: string;
  provider: string;
  kind: NationalDatasetKind;
  phase: NationalDatasetPhase;
  envKey:
    | "MOLIT_SERVICE_KEY"
    | "SEOUL_DATA_API_KEY"
    | "DATA_GO_KR_SERVICE_KEY"
    | "EX_DATA_API_KEY"
    | "KOSIS_SERVICE_KEY"
    | "NONE";
  matchTitles: string[];
  utilization: string;
  appSurfaces: string;
  portalUrl?: string;
  integrationStatus: NationalIntegrationStatus;
  ttlHours: number;
};

const PLANS: NationalUtilizationPlan[] = [
  {
    id: "molit-apt-sale",
    title: "아파트 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_아파트 매매 실거래가 자료", "아파트 매매 실거래"],
    utilization: "지역·단지 시세 추이, /map/price, AI 비교 입력",
    appSurfaces: "/map/price, /explore, /property-search",
    portalUrl: "https://www.data.go.kr/data/15057511/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-apt-rent",
    title: "아파트 전월세 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_아파트 전월세 실거래가 자료"],
    utilization: "전세·월세 임장, 임대 수익률 참고",
    appSurfaces: "/property-search, /explore",
    portalUrl: "https://www.data.go.kr/data/15057511/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-apt-sale-detail",
    title: "아파트 매매 실거래 상세",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_아파트 매매 실거래가 상세 자료"],
    utilization: "층·면적·거래일 단위 임장노트 prefill",
    appSurfaces: "/info/apt/[id], /inspection/create",
    integrationStatus: "planned",
    ttlHours: 24,
  },
  {
    id: "molit-offi-sale",
    title: "오피스텔 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_오피스텔 매매 실거래가 자료"],
    utilization: "오피스텔 시세·임장, 수익형 비교",
    appSurfaces: "/property-search, /explore, /inspection",
    portalUrl: "https://www.data.go.kr/data/15058453/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-offi-rent",
    title: "오피스텔 전월세 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_오피스텔 전월세 실거래가 자료"],
    utilization: "오피스텔 임대 수익률·전월세 참고",
    appSurfaces: "/property-search, /explore",
    portalUrl: "https://www.data.go.kr/data/15058452/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-rh-sale",
    title: "연립다세대 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_연립다세대 매매 실거래가 자료"],
    utilization: "빌라·다세대 시세, 갭투자·전세가율 참고",
    appSurfaces: "/property-search, /explore, /inspection",
    portalUrl: "https://www.data.go.kr/data/15058038/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-sh-sale",
    title: "단독/다가구 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_단독/다가구 매매 실거래가 자료"],
    utilization: "단독·다가구 토지+건물 시세 참고",
    appSurfaces: "/property-search, /explore",
    portalUrl: "https://www.data.go.kr/data/15058022/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-sh-rent",
    title: "단독/다가구 전월세 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_단독/다가구 전월세 실거래가 자료"],
    utilization: "단독·다가구 전월세 참고",
    appSurfaces: "/property-search, /explore",
    portalUrl: "https://www.data.go.kr/data/15058021/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-land-sale",
    title: "토지 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_토지 매매 실거래가 자료"],
    utilization: "지목·용도별 토지 시세, 개발 참고",
    appSurfaces: "/explore, /inspection",
    portalUrl: "https://www.data.go.kr/data/15058019/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-silv-sale",
    title: "아파트 분양권전매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_아파트 분양권전매 실거래가 자료"],
    utilization: "분양권 프리미엄·전매 시세 참고",
    appSurfaces: "/explore, /property-search",
    portalUrl: "https://www.data.go.kr/data/15058024/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-nrg-sale",
    title: "상업업무용 매매 실거래가",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_상업업무용 부동산 매매 실거래가 자료"],
    utilization: "상가·업무용 시세, 수익형 투자 참고",
    appSurfaces: "/explore, /property-search",
    portalUrl: "https://www.data.go.kr/data/15058453/openapi.do",
    integrationStatus: "live",
    ttlHours: 24,
  },
  {
    id: "molit-building-registry",
    title: "건축물대장",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_건축HUB_건축물대장정보 서비스", "건축물대장"],
    utilization: "준공년도·용도·면적 검증, 단지 카드",
    appSurfaces: "/info/apt/[id], /inspection/hub",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "molit-geocoder",
    title: "지오코더·주소 변환",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_지오코더 API", "지오코더"],
    utilization: "임장 GPS→주소, 지도 마커 정규화",
    appSurfaces: "/info/map, /explore, /inspection/create",
    portalUrl: "https://www.data.go.kr/data/15084084/openapi.do",
    integrationStatus: "planned",
    ttlHours: 720,
  },
  {
    id: "molit-cadastral",
    title: "연속지적도",
    provider: "국토교통부",
    kind: "openapi",
    phase: 1,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_연속지적도"],
    utilization: "필지 경계·토지 임장 레이어",
    appSurfaces: "/info/map, /info/redevelopment",
    integrationStatus: "planned",
    ttlHours: 720,
  },
  {
    id: "address-juso",
    title: "실시간 주소 검색",
    provider: "행정안전부",
    kind: "openapi",
    phase: 1,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: [
      "행정안전부_실시간 주소정보 조회",
      "행정안전부_실시간 주소정보 조회(검색API)",
      "주소정보 조회",
    ],
    utilization: "글쓰기·임장노트 주소 자동완성",
    appSurfaces: "/community/write, /inspection/create",
    integrationStatus: "planned",
    ttlHours: 720,
  },
  {
    id: "seoul-subway-arrival",
    title: "서울 지하철 실시간 도착",
    provider: "서울특별시",
    kind: "openapi",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    matchTitles: ["서울특별시_지하철 실시간 도착정보"],
    utilization: "교통·접근성 점수, 임장 동선 ETA",
    appSurfaces: "/transport-access, /explore",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "seoul-bus-location",
    title: "서울 버스 위치정보",
    provider: "서울특별시",
    kind: "openapi",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    matchTitles: ["서울특별시_버스위치정보조회 서비스"],
    utilization: "버스 접근성·현장 이동 시간",
    appSurfaces: "/transport-access, /field",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "ex-congestion-frequency",
    title: "고속도로 혼잡빈도",
    provider: "한국도로공사",
    kind: "file",
    phase: 1,
    envKey: "EX_DATA_API_KEY",
    matchTitles: ["한국도로공사_혼잡빈도", "혼잡빈도"],
    utilization: "장거리 임장·출퇴근 경로 혼잡 회피",
    appSurfaces: "/transport-access, /field",
    portalUrl: "https://www.data.go.kr/data/15045664/fileData.do",
    integrationStatus: "live",
    ttlHours: 720,
  },
  {
    id: "applyhome-competition",
    title: "청약홈 경쟁률·특별공급",
    provider: "한국부동산원",
    kind: "openapi",
    phase: 1,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: [
      "청약홈 청약접수 경쟁률",
      "ApplyhomeInfoCmpetRtSvc",
      "분양정보/경쟁률",
    ],
    utilization: "APT·오피스텔 분양 경쟁률, 특별공급 신청현황",
    appSurfaces: "/presale, /calculator/subscription-points",
    portalUrl: "https://www.data.go.kr/data/15125682/openapi.do",
    integrationStatus: "live",
    ttlHours: 1,
  },
  {
    id: "air-quality",
    title: "에어코리아 대기오염",
    provider: "한국환경공단",
    kind: "openapi",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["한국환경공단_에어코리아_대기오염정보", "에어코리아"],
    utilization: "생활환경·건강 지표, 임장 일정 조정",
    appSurfaces: "/explore, /transport-access",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "weather-short",
    title: "기상청 단기예보",
    provider: "기상청",
    kind: "openapi",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["기상청_단기예보 조회서비스"],
    utilization: "임장·현장 일정 날씨 배너",
    appSurfaces: "/field, /inspection/hub",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "commercial-district",
    title: "전국 상가(상권)정보",
    provider: "소상공인시장진흥공단",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["소상공인시장진흥공단_상가(상권)정보", "상가(상권)정보"],
    utilization: "상권 활성·업종 분포, 동네 경제 지표",
    appSurfaces: "/explore, /market",
    portalUrl: "https://www.data.go.kr/data/15083005/fileData.do",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "parking-standard",
    title: "전국 주차장 표준데이터",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국주차장정보표준데이터"],
    utilization: "임장 주차 POI, 차량 보유 가구 참고",
    appSurfaces: "/info/map, /inspection/create",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "city-park-standard",
    title: "전국 도시공원",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국도시공원정보표준데이터"],
    utilization: "생활환경·녹지 접근성",
    appSurfaces: "/explore, /api/inspection/nearby-facilities",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "childcare-zone",
    title: "전국 어린이보호구역",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국어린이보호구역표준데이터"],
    utilization: "학군·안전 임장 체크리스트",
    appSurfaces: "/explore, /inspection/hub",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "public-facility-open",
    title: "전국 공공시설 개방",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국공공시설개방정보표준데이터"],
    utilization: "주민센터·체육시설 등 생활 인프라",
    appSurfaces: "/explore, /community",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "multi-use-business",
    title: "다중이용업소(소방)",
    provider: "소방청",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: [
      "소방청_다중이용업소",
      "소방청_다중이용업소 영업장별 고유 일련번호",
      "다중이용업소",
    ],
    utilization: "상권 안전·유흥업소 밀집 참고",
    appSurfaces: "/explore",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "culture-festival",
    title: "전국 문화축제",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국문화축제표준데이터", "전국공연행사정보표준데이터"],
    utilization: "동네 이벤트·유동 인구 맥락",
    appSurfaces: "/community, /meeting-market",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "tourism-info",
    title: "관광정보(한국관광공사)",
    provider: "한국관광공사",
    kind: "openapi",
    phase: 2,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["한국관광공사_국문 관광정보 서비스", "한국관광공사_국문 관광정보 서비스_GW"],
    utilization: "근교·생활권 관광 POI",
    appSurfaces: "/explore, /info/map",
    integrationStatus: "planned",
    ttlHours: 24,
  },
  {
    id: "traffic-cctv",
    title: "교통 CCTV·화상",
    provider: "국토교통부",
    kind: "openapi",
    phase: 3,
    envKey: "MOLIT_SERVICE_KEY",
    matchTitles: ["국토교통부_교통CCTV", "국토교통부_CCTV 화상자료"],
    utilization: "출퇴근·임장 전 구간 소통 확인",
    appSurfaces: "/transport-access",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "jeju-traffic",
    title: "제주 실시간 교통",
    provider: "제주특별자치도",
    kind: "openapi",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["제주특별자치도_실시간  교통정보", "제주특별자치도_실시간 교통정보"],
    utilization: "광역 임장·이주 타겟 지역 교통",
    appSurfaces: "/transport-access",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "pension-business",
    title: "국민연금 가입 사업장",
    provider: "국민연금공단",
    kind: "file",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["국민연금공단_국민연금 가입 사업장 내역"],
    utilization: "일자리·상권 밀집(사업장 수) proxy",
    appSurfaces: "/explore, /reports",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "construction-pension",
    title: "건설근로자 퇴직공제 사업장",
    provider: "건설근로자공제회",
    kind: "file",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["건설근로자공제회_퇴직공제 가입사업장 정보"],
    utilization: "재개발·신축 현장 수요 맥락",
    appSurfaces: "/info/redevelopment",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "stock-price",
    title: "금융위 주식시세",
    provider: "금융위원회",
    kind: "openapi",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["금융위원회_주식시세정보"],
    utilization: "투자·거시 맥락 리포트(참고)",
    appSurfaces: "/reports, /ai-analysis",
    integrationStatus: "planned",
    ttlHours: 1,
  },
  {
    id: "bid-info",
    title: "나라장터 입찰·낙찰",
    provider: "조달청",
    kind: "openapi",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["조달청_나라장터 입찰공고정보서비스", "조달청_나라장터 낙찰정보서비스"],
    utilization: "공공·인프라 공사 파이프라인",
    appSurfaces: "/reports, /admin",
    integrationStatus: "planned",
    ttlHours: 24,
  },
  {
    id: "special-day",
    title: "천문연구원 특일 정보",
    provider: "한국천문연구원",
    kind: "openapi",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["한국천문연구원_특일 정보"],
    utilization: "연휴·대체공휴일 임장 일정",
    appSurfaces: "/field, /inspection/hub",
    integrationStatus: "planned",
    ttlHours: 720,
  },
  {
    id: "portal-open-status",
    title: "공공데이터 목록개방현황",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 3,
    envKey: "NONE",
    matchTitles: [
      "공공데이터활용지원센터_공공데이터포털 목록개방현황",
      "공공데이터포털 목록개방현황",
    ],
    utilization: "신규 데이터셋 발굴·로드맵 갱신",
    appSurfaces: "/admin/public-data, /admin/settings",
    integrationStatus: "sample",
    ttlHours: 168,
  },
  {
    id: "lifelong-learning",
    title: "전국 평생학습 강좌",
    provider: "공공데이터활용지원센터",
    kind: "file",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["전국평생학습강좌표준데이터"],
    utilization: "동네 교육·커뮤니티 프로그램",
    appSurfaces: "/community, /meeting-market",
    integrationStatus: "planned",
    ttlHours: 168,
  },
  {
    id: "imu-road-sensor",
    title: "인천 도로 IMU 센서",
    provider: "인천광역시",
    kind: "file",
    phase: 3,
    envKey: "DATA_GO_KR_SERVICE_KEY",
    matchTitles: ["인천광역시_도로 내 IMU 센서"],
    utilization: "도로 상태·교통 센서 파일 연구용",
    appSurfaces: "/transport-access, /reports",
    integrationStatus: "planned",
    ttlHours: 168,
  },
];

export type NationalUtilizationPlanWithScore = NationalUtilizationPlan & {
  popularityScore: number;
  popularityAppearances: number;
  popularityBestRank: number | null;
  popularityLists: string[];
};

export function getNationalUtilizationCatalog(): NationalUtilizationPlanWithScore[] {
  return PLANS.map((plan) => {
    const pop = scorePopularity(plan.matchTitles);
    return {
      ...plan,
      popularityScore: pop.score,
      popularityAppearances: pop.appearances,
      popularityBestRank: pop.bestRank,
      popularityLists: pop.lists,
    };
  }).sort((a, b) => b.popularityScore - a.popularityScore || a.phase - b.phase);
}

export const NATIONAL_UTILIZATION_CATALOG = PLANS;

export function getNationalPlanById(id: string): NationalUtilizationPlanWithScore | undefined {
  return getNationalUtilizationCatalog().find((p) => p.id === id);
}

export function resolveNationalIntegrationStatus(
  plan: NationalUtilizationPlan,
): NationalIntegrationStatus {
  if (plan.integrationStatus === "live" || plan.integrationStatus === "sample") {
    return plan.integrationStatus;
  }
  const runtime = getNationalPlanCapability(plan.id);
  if (runtime !== "planned") return runtime;
  if (plan.envKey !== "NONE" && process.env[plan.envKey]?.trim()) {
    return "partial";
  }
  return plan.integrationStatus;
}
