/**
 * 서울 공공데이터 30종 카탈로그 (생활편의·임장 중심).
 */

export type SeoulDatasetPhase = 1 | 2 | 3;
export type SeoulDatasetStatus = "live" | "partial" | "stub" | "unavailable";

export type SeoulDatasetMeta = {
  id: string;
  title: string;
  serviceName: string;
  oaUrl?: string;
  provider: string;
  phase: SeoulDatasetPhase;
  envKey:
    | "SEOUL_DATA_API_KEY"
    | "VWORLD_API_KEY"
    | "MOLIT_SERVICE_KEY"
    | "REB_SERVICE_KEY"
    | "SCHOOLINFO_API_KEY"
    | "EX_DATA_API_KEY";
  ttlHours: number;
  license: string;
  usage: string;
  knownIssues?: string;
};

export const SEOUL_DATASET_CATALOG: SeoulDatasetMeta[] = [
  {
    id: "upis-rebuild",
    title: "정비사업(재개발·재건축)",
    serviceName: "upisRebuild",
    oaUrl: "https://data.seoul.go.kr/",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "/info/redevelopment, 지도 레이어, 임장 리스크",
  },
  {
    id: "rtms-sale",
    title: "부동산 실거래가",
    serviceName: "tbLnOpendataRtmsM",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-21275/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 24,
    license: "공공누리 1유형",
    usage: "/map/price, 지역 상세, AI 비교",
    knownIssues: "tbLnOpendataRtmsM 장애 시 전월세(tbLnOpendataRtmsV) 프록시",
  },
  {
    id: "rtms-rent",
    title: "부동산 전월세가",
    serviceName: "tbLnOpendataRtmsV",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-21276/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 24,
    license: "공공누리 1유형",
    usage: "전세/월세 임장, /property-search",
  },
  {
    id: "apt-info",
    title: "공동주택 아파트 정보",
    serviceName: "tbSeoulAptInfo",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-15818/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "/info/apt/[id] 단지 프로필",
    knownIssues: "API ERROR-500 — 키 설정 시 재시도",
  },
  {
    id: "land-price",
    title: "개별공시지가",
    serviceName: "landPriceInfo",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-1180/F/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 720,
    license: "공공누리 1유형",
    usage: "토지 가치·재개발 잠재, 임장노트",
    knownIssues: "API ERROR-500 — 키 설정 시 재시도",
  },
  {
    id: "broker",
    title: "부동산 중개업소",
    serviceName: "tbPropertyBrokerInfo",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-15550/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "지도 POI, 현장 중개사무소",
    knownIssues: "API ERROR-500 — 키 설정 시 재시도",
  },
  {
    id: "standard-price",
    title: "시가표준액",
    serviceName: "tbStandardPrice",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-12852/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 720,
    license: "변경금지 — 상업 이용 주의",
    usage: "세금·기준가 참고",
  },
  {
    id: "global-broker",
    title: "전국 부동산중개업 (국토부)",
    serviceName: "LT_C_REBOPNBRKRUPINFO",
    oaUrl: "https://www.data.go.kr/data/15123990/openapi.do",
    provider: "브이월드 · 국토교통부",
    phase: 2,
    envKey: "VWORLD_API_KEY",
    ttlHours: 168,
    license: "공공누리",
    usage: "지도 POI, 전국 중개사무소, `/api/public-data/brokers`",
    knownIssues: "VWorld 키 발급 시 「부동산중개업정보」 API 활성화 필요",
  },
  {
    id: "hospital",
    title: "병원·의료",
    serviceName: "TbHospitalInfo",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "편의시설 카운트, 500m 임장 체크",
  },
  {
    id: "pharmacy",
    title: "약국",
    serviceName: "TbPharmacyOperateInfo",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "야간/24h 약국 레이어",
  },
  {
    id: "childcare",
    title: "어린이집·보육",
    serviceName: "ChildCareInfo",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "육아 동네 적합도",
  },
  {
    id: "school",
    title: "학교 위치",
    serviceName: "schoolInfo",
    provider: "교육청·학교알리미",
    phase: 3,
    envKey: "SCHOOLINFO_API_KEY",
    ttlHours: 168,
    license: "NEIS Open API",
    usage: "학군·통학 임장",
  },
  {
    id: "park",
    title: "공원",
    serviceName: "SearchParkInfoService",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "녹지·산책로, 임장 동선",
  },
  {
    id: "subway",
    title: "지하철역",
    serviceName: "SearchSTNBySubwayLineInfo",
    provider: "서울 열린데이터광장",
    phase: 1,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "역세권 점수, /transport-access",
  },
  {
    id: "bus",
    title: "버스정류소",
    serviceName: "busStationLocation",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "버스 접근성",
    knownIssues: "ERROR-500 — ws.bus.go.kr 별도 키 필요",
  },
  {
    id: "parking",
    title: "공영주차장",
    serviceName: "GetParkInfo",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "임장 주차·주변 주차비",
  },
  {
    id: "bike",
    title: "공공자전거(따릉이)",
    serviceName: "bikeStation",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 24,
    license: "공공누리 1유형",
    usage: "역 주변 이동 수단",
  },
  {
    id: "market",
    title: "전통시장",
    serviceName: "TbMarket",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "생활권·상권",
  },
  {
    id: "mart",
    title: "대형마트",
    serviceName: "TbMart",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "생활편의",
  },
  {
    id: "library",
    title: "도서관",
    serviceName: "SeoulLibraryInfo",
    provider: "서울 열린데이터광장",
    phase: 2,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "문화·학습 인프라",
    knownIssues: "ERROR-500 — 키 설정 시 재시도",
  },
  {
    id: "culture",
    title: "문화시설",
    serviceName: "SeoulCulturalFacilityInfo",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "극장·박물관",
  },
  {
    id: "sports",
    title: "체육시설",
    serviceName: "SeoulSportsFacilityInfo",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "운동·커뮤니티",
  },
  {
    id: "fire-station",
    title: "119 안전센터",
    serviceName: "Tb119RescueteamInfo",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "안전·재난 참고",
  },
  {
    id: "traffic-inconvenience",
    title: "통행불편지역",
    serviceName: "trafficInconvenience",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-21207/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "공사·우회, route-planner",
  },
  {
    id: "cadastral",
    title: "지적재조사",
    serviceName: "cadastralResurvey",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-21206/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "필지·경계 확인",
  },
  {
    id: "expropriation",
    title: "수용재결 사업진행",
    serviceName: "expropriationProgress",
    oaUrl: "https://data.seoul.go.kr/dataList/OA-2541/S/1/datasetView.do",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 168,
    license: "공공누리 1유형",
    usage: "재개발 인근 보상 맥락",
  },
  {
    id: "cctv-traffic",
    title: "교통 CCTV/소통",
    serviceName: "cctvTraffic",
    provider: "서울 열린데이터광장",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 1,
    license: "공공누리 1유형",
    usage: "임장 시간대 혼잡도(참고)",
  },
  {
    id: "floating-population",
    title: "생활인구(체류)",
    serviceName: "seoulBigdataFloating",
    provider: "서울빅데이터",
    phase: 3,
    envKey: "SEOUL_DATA_API_KEY",
    ttlHours: 24,
    license: "별도 신청",
    usage: "유동·상권 활성",
  },
  {
    id: "molit-apt-trade",
    title: "국토부 아파트 실거래",
    serviceName: "molitAptTrade",
    provider: "국토교통부",
    phase: 3,
    envKey: "MOLIT_SERVICE_KEY",
    ttlHours: 24,
    license: "공공데이터포털",
    usage: "서울 데이터 교차검증",
  },
  {
    id: "reb-weekly",
    title: "한국부동산원 주간동향",
    serviceName: "rebWeeklyTrend",
    provider: "한국부동산원",
    phase: 3,
    envKey: "REB_SERVICE_KEY",
    ttlHours: 168,
    license: "REB Open API",
    usage: "주간 시세 변동, 홈 위젯",
  },
  {
    id: "ex-congestion-frequency",
    title: "고속도로 혼잡빈도",
    serviceName: "exCongestionFrequency",
    oaUrl: "https://www.data.go.kr/data/15045664/fileData.do",
    provider: "한국도로공사",
    phase: 2,
    envKey: "EX_DATA_API_KEY",
    ttlHours: 720,
    license: "이용허락범위 제한 없음",
    usage: "/transport-access, /field 임장 동선, 출퇴근·장거리 이동",
    knownIssues:
      "전국 CSV(월 520만행)는 data.ex.co.kr 월별 다운로드 — 앱은 공식 샘플·수도권 구간",
  },
];

export const PUBLIC_DATA_SOURCES = SEOUL_DATASET_CATALOG.slice(0, 4).map((d) => ({
  id: d.id,
  title: d.title,
  provider: d.provider,
  note: d.usage,
}));

export const BATCH_GUIDE =
  "실거래/전월세: 24h · upisRebuild·편의시설: 7d · 공시지가: 30d";

export function getDatasetStatus(
  meta: SeoulDatasetMeta,
  liveServices: Set<string>,
): SeoulDatasetStatus {
  if (meta.id === "ex-congestion-frequency") return "live";
  const envOk = Boolean(process.env[meta.envKey]?.trim());
  if (!envOk) return "stub";
  if (meta.phase === 3) return "stub";
  if (liveServices.has(meta.serviceName)) return "live";
  if (meta.knownIssues) return "partial";
  return meta.phase <= 2 ? "partial" : "stub";
}
