/* 코드가 참조하지만 DB 에 없던 테이블 5개 · 컬럼 7개를 추가한다.

   왜: 스윕 결과, 아래 다섯 테이블과 app_users 의 일곱 컬럼이 코드에만 존재했다.
   그 결과가 "오류"로 보이지 않았다는 게 진짜 문제다 —
     · /api/map/workspace, /api/map/district-snapshot 은 districts/district_snapshots
       가 없어 100% 503 (dbUnavailable 로 감싸 runtime error 목록에도 안 뜬다),
     · /api/complex/[id]/snapshot 은 partner_listings/nearby_provider_links 조회
       error 를 `?? []` 로 삼켜 "매물 없음 · 주변 전문가 없음"을 사실처럼 답했고,
     · /api/me/regions 는 app_users.watch_regions 가 없어 GET 503 · PUT 500,
       즉 관심 지역은 한 번도 저장된 적이 없으며,
     · 토스/카카오 로그인은 연동 컬럼이 없어 조회·갱신이 매번 실패했다.
   조회 실패를 "데이터 없음"으로 답하지 않는다는 원칙을 지키려면, 먼저 조회가
   가능해야 한다. 그래서 스키마를 사실에 맞춘다.

   추가만 한다 — drop/truncate 없음, 전부 if not exists 로 재실행 가능.
   districts 시드는 실제 public.legal_regions(265행) 에서만 가져온다.
   지어낸 행은 넣지 않는다. 시도 전체 명칭은 행정구역 공식 명칭이라 결정적이다. */

-- ─────────────────────────── 1) districts ───────────────────────────
create table if not exists public.districts (
  id          bigint generated by default as identity primary key,
  lawd_cd     text not null,
  sido        text not null,        -- 공식 전체 명칭 (예: 서울특별시)
  sido_short  text not null,        -- legal_regions.sido 원본 (예: 서울)
  sigungu     text not null,
  eupmyeondong text,
  display_name text,
  lat         double precision,
  lng         double precision,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index if not exists districts_lawd_cd_key
  on public.districts (lawd_cd);
/* (시도, 시군구) 는 유일하지 않다. 법정동코드 재편으로 옛 코드와 새 코드가 함께
   남은 행이 실제로 2쌍 있다(시흥시 41390/41430, 전주시 완산구 45111/52111).
   어느 쪽이 정본인지는 소유자 판단이므로 지우지 않고, 조회는 lawd_cd 오름차순
   첫 행으로 결정적으로 고른다. 그래서 여기는 unique 가 아니다. */
create index if not exists districts_sido_short_sigungu_idx
  on public.districts (sido_short, sigungu);
create index if not exists districts_sido_sigungu_idx
  on public.districts (sido, sigungu);

insert into public.districts (lawd_cd, sido, sido_short, sigungu, display_name, lat, lng)
select
  r.lawd_cd,
  case r.sido
    when '서울' then '서울특별시'
    when '부산' then '부산광역시'
    when '대구' then '대구광역시'
    when '인천' then '인천광역시'
    when '광주' then '광주광역시'
    when '대전' then '대전광역시'
    when '울산' then '울산광역시'
    when '세종' then '세종특별자치시'
    when '경기' then '경기도'
    when '강원' then '강원특별자치도'
    when '충북' then '충청북도'
    when '충남' then '충청남도'
    when '전북' then '전북특별자치도'
    when '전남' then '전라남도'
    when '경북' then '경상북도'
    when '경남' then '경상남도'
    when '제주' then '제주특별자치도'
    else r.sido
  end,
  r.sido,
  r.sigungu,
  r.display_name,
  nullif(r.lat::text, '')::double precision,
  nullif(r.lng::text, '')::double precision
from public.legal_regions r
where r.lawd_cd is not null and r.sigungu is not null and r.sigungu <> ''
on conflict (lawd_cd) do nothing;

-- ─────────────────────── 2) district_snapshots ──────────────────────
create table if not exists public.district_snapshots (
  id           bigint generated by default as identity primary key,
  district_id  bigint not null references public.districts(id) on delete cascade,
  snapshot_ym  text not null,
  metric_group text not null,
  payload      jsonb not null default '{}'::jsonb,
  source_authority text,
  source_url   text,
  fetched_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
/* upsertDistrictSnapshotDocument 가 onConflict:"district_id,snapshot_ym,metric_group"
   로 올린다 — 이 unique 가 없으면 upsert 자체가 실패한다. */
create unique index if not exists district_snapshots_key
  on public.district_snapshots (district_id, snapshot_ym, metric_group);

-- ───────────────────────── 3) partner_listings ──────────────────────
create table if not exists public.partner_listings (
  id              bigint generated by default as identity primary key,
  complex_id      text not null,
  title           text not null,
  sale_type       text not null default 'sale',
  deposit_krw     bigint,
  monthly_rent_krw bigint,
  sale_price_krw  bigint,
  area_m2         numeric,
  status          text not null default 'active',
  external_source text not null default 'partner',
  external_key    text,
  last_seen_at    timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists partner_listings_complex_status_idx
  on public.partner_listings (complex_id, status, last_seen_at desc);
create unique index if not exists partner_listings_external_key_key
  on public.partner_listings (external_key) where external_key is not null;

-- ────────────────────── 4) nearby_provider_links ────────────────────
create table if not exists public.nearby_provider_links (
  id         bigint generated by default as identity primary key,
  complex_id text not null,
  expert_id  uuid not null references public.expert_profiles(id) on delete cascade,
  link_type  text not null default 'nearby',
  distance_m integer,
  created_at timestamptz not null default now()
);
create index if not exists nearby_provider_links_complex_idx
  on public.nearby_provider_links (complex_id);
create unique index if not exists nearby_provider_links_key
  on public.nearby_provider_links (complex_id, expert_id, link_type);

-- ───────────────────────── 5) toss_login_tokens ─────────────────────
create table if not exists public.toss_login_tokens (
  user_key      text primary key,
  access_token  text,
  refresh_token text,
  token_type    text,
  scope         text,
  expires_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ───────────────────────── 6) app_users 컬럼 ────────────────────────
alter table public.app_users
  add column if not exists watch_regions jsonb not null default '[]'::jsonb,
  add column if not exists toss_user_key text,
  add column if not exists toss_ci text,
  add column if not exists toss_linked_at timestamptz,
  add column if not exists toss_unlinked_at timestamptz,
  add column if not exists kakao_user_id text,
  add column if not exists kakao_linked_at timestamptz;

create unique index if not exists app_users_toss_user_key_key
  on public.app_users (toss_user_key) where toss_user_key is not null;
create unique index if not exists app_users_kakao_user_id_key
  on public.app_users (kakao_user_id) where kakao_user_id is not null;

-- ───────────────────────────── RLS ──────────────────────────────────
alter table public.districts            enable row level security;
alter table public.district_snapshots   enable row level security;
alter table public.partner_listings     enable row level security;
alter table public.nearby_provider_links enable row level security;
alter table public.toss_login_tokens    enable row level security;

/* districts · district_snapshots 는 공개 참조 자료 — 읽기만 연다. */
do $$ begin
  if not exists (select 1 from pg_policies
                 where schemaname='public' and tablename='districts'
                   and policyname='districts_public_read') then
    create policy districts_public_read on public.districts
      for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies
                 where schemaname='public' and tablename='district_snapshots'
                   and policyname='district_snapshots_public_read') then
    create policy district_snapshots_public_read on public.district_snapshots
      for select to anon, authenticated using (true);
  end if;
  /* 매물은 게시 중인 것만 공개한다. */
  if not exists (select 1 from pg_policies
                 where schemaname='public' and tablename='partner_listings'
                   and policyname='partner_listings_public_read_active') then
    create policy partner_listings_public_read_active on public.partner_listings
      for select to anon, authenticated using (status = 'active');
  end if;
  if not exists (select 1 from pg_policies
                 where schemaname='public' and tablename='nearby_provider_links'
                   and policyname='nearby_provider_links_public_read') then
    create policy nearby_provider_links_public_read on public.nearby_provider_links
      for select to anon, authenticated using (true);
  end if;
end $$;

/* toss_login_tokens 에는 정책을 만들지 않는다 — RLS 가 켜져 있고 정책이 없으면
   anon·authenticated 는 한 행도 못 읽는다. 토큰은 service_role 만 다룬다. */

comment on table public.districts is
  '행정구역(시도·시군구) 참조 테이블 — public.legal_regions 에서 시드. 지역 스냅샷 조인 키.';
comment on table public.toss_login_tokens is
  '토스 로그인 토큰 — service_role 전용(RLS 정책 없음).';
